### ISSUE TITLE
Output timestamp instead of a formatted string

### ISSUE THREAD

**Issue by westenberg** [frenck/python-twentemilieu#224]
Currently the output is a formatted which you can't localise without template sensor in Home Assistant. By leaving this a timestamp we can add device_class timestamp in Home Assistant.

I can make the adjustment, just curious if this is perhaps a formatted string by purpose.

**Comment by frenck** [comment]
The use of a time is weird in this context, as it is a date, not a date +time. Setting a timestamp device class will cause the frontend to show a relative time, which will look weird.

Also, that is a Home Assistant discussion, not a library problem I would say.

**Comment by westenberg** [comment]
Fully agree, thanks!
