### ISSUE TITLE
Multiple identical _pickupTypeText's should be merged

### ISSUE THREAD

**Issue by olafz** [frenck/python-twentemilieu#3]
I got to this library because of the integration with HomeAssistant. Good stuff!

However, the Paper pickup is _unknown_:

![image](https://user-images.githubusercontent.com/80709/62880219-34e34b80-bd2d-11e9-83db-bbea1a5d8696.png)

After debugging the API, I found the cause. For my address, the following snippet of JSON is returned for the `"_pickupTypeText" : "PAPER"`:

```json
      {  
         "pickupDates":[  
            "2019-08-29T00:00:00"
         ],
         "pickupType":0,
         "_pickupType":0,
         "_pickupTypeText":"PAPER",
         "description":"EN PAP DO42"
      },
      {  
         "pickupDates":[  

         ],
         "pickupType":0,
         "_pickupType":0,
         "_pickupTypeText":"PAPER",
         "description":"EN PAP DO42_"
      }
```

The lines of code in the parser, override the second (empty) `pickupDates` from the first:

https://github.com/frenck/python-twentemilieu/blob/77bd609ac6fa25ce0d7d2eecaf04a09effa2c216/twentemilieu/twentemilieu.py#L135-L142

I'm not sure if this happens to other `_pickupTypeText`'s as well, but I think the identical `_pickupTypeText` values should be merged instead of overridden.

**Comment by ErikvO** [comment]
I have the same issue where a 2nd _pickupTypeText overwrites the first one. In my case the first one was filled with data and had the first upcoming date. This was overwritten by the second instance.

See response below where both GREY and GREEN are incorrectly overwritten with later dates.
Also: the response contains another type: TREE, which is the pickup date for Christmas trees. It might be nice to include this type in the library.

``` json
{
	"userMessage": {
		"type": null,
		"messageCode": 0,
		"description": null
	},
	"ExtraOption": {
		"$type": "System.Dynamic.ExpandoObject, System.Core"
	},
	"dataList": [{
			"pickupDates": ["2020-12-14T00:00:00", "2020-12-28T00:00:00"],
			"pickupType": 0,
			"_pickupType": 0,
			"_pickupTypeText": "PACKAGES",
			"description": "EN AL01 OVMA"
		}, {
			"pickupDates": ["2020-12-08T00:00:00", "2020-12-22T00:00:00"],
			"pickupType": 0,
			"_pickupType": 0,
			"_pickupTypeText": "GREY",
			"description": "EN AL02 ERDI"
		}, {
			"pickupDates": ["2020-12-15T00:00:00", "2020-12-29T00:00:00"],
			"pickupType": 0,
			"_pickupType": 0,
			"_pickupTypeText": "GREEN",
			"description": "EN AL02 OGDI"
		}, {
			"pickupDates": ["2021-01-12T00:00:00", "2021-01-26T00:00:00", "2021-02-09T00:00:00", "2021-02-23T00:00:00", "2021-03-09T00:00:00"],
			"pickupType": 0,
			"_pickupType": 0,
			"_pickupTypeText": "GREEN",
			"description": "EN A02 G2AC"
		}, {
			"pickupDates": ["2021-01-05T00:00:00", "2021-02-02T00:00:00", "2021-03-02T00:00:00"],
			"pickupType": 0,
			"_pickupType": 0,
			"_pickupTypeText": "GREY",
			"description": "EN A02 R2B"
		}, {
			"pickupDates": ["2021-01-11T00:00:00"],
			"pickupType": 0,
			"_pickupType": 0,
			"_pickupTypeText": "TREE",
			"description": "EN KERST LMA"
		}, {
			"pickupDates": ["2021-01-13T00:00:00", "2021-02-10T00:00:00", "2021-03-10T00:00:00"],
			"pickupType": 0,
			"_pickupType": 0,
			"_pickupTypeText": "PAPER",
			"description": "EN PAP WO22"
		}
	],
	"intDataList": null,
	"data": null,
	"status": true,
	"messageCode": 107,
	"pdfResponse": null,
	"token": null,
	"ID": null,
	"invalidParameters": null,
	"total": 0,
	"messageToString": null
}
```

**Comment by ErikvO** [comment]
I looked into it and I think I have a solution.
Note: I'm not a Python coder, so I'm not 100% sure about the syntax, but I think something along the lines of this might fix the issue:
``` python
previous_pickup_date = self._pickup.get(waste_type)
if previous_pickup_date is not None:
    pickup_date = min(pickup_date, previous_pickup_date)
```

Which will look like this in the context of the surrounding code:
``` python
for pickup in response["dataList"]:
    waste_type = API_TO_WASTE_TYPE.get(pickup["_pickupTypeText"])
    pickup_date = None
    if pickup["pickupDates"]:
        pickup_date = datetime.strptime(
            min(pickup["pickupDates"]), "%Y-%m-%dT%H:%M:%S"
        )

    previous_pickup_date = self._pickup.get(waste_type)
    if previous_pickup_date is not None:
        pickup_date = min(pickup_date, previous_pickup_date)

    self._pickup.update({waste_type: pickup_date})  # type: ignore
```

As I normally don't code in Python, I do not have anything set up to test this change. Which is the reason I have not made a proper pull request out of it. I hope you can use it though.
