### ISSUE TITLE
ImportError: cannot import name 'TwenteMilieu'

### ISSUE THREAD

**Issue by gewoonandre** [frenck/python-twentemilieu#367]
# Problem/Motivation

> I tried to get this working on RPI3 and RPI4, both running Openhabian OS, which is based on Linux bullseye. Unfortunately I don't get it working. 

## Expected behavior

> By using the example.py I expected to get some dates on the screen. Python v3.9.2 is installed.

## Actual behavior

> By running the example.py,  following error is shown:

Traceback (most recent call last):
  File "/opt/twentemilieu/example.py", line 6, in <module>
    from twentemilieu import TwenteMilieu, WasteType
  File "/opt/twentemilieu/twentemilieu.py", line 3, in <module>
    from twentemilieu import TwenteMilieu, WasteType
ImportError: cannot import name 'TwenteMilieu' from partially initialized module 'twentemilieu' (most likely due to a circular import) (/opt/twentemilieu/twentemilieu.py)

Did I forget something important during installation?

**Comment by frenck** [comment]
I don't see a circular import in this integration?

This library is actively used by Home Assistant as well:

<https://github.com/home-assistant/core/blob/master/homeassistant/components/twentemilieu/__init__.py#L29-L34>

**Comment by gewoonandre** [comment]
By reading my own post again, i found it! Feeling really dumb now, haha.
I saved the initial "exmple.py" as "twentemilieu.py" and put them both in the same folder. 

Removed the "twentemilieu.py" which contained the example code and its working now! Thank you very much anyway!
