### ISSUE TITLE
Please add Gemeente Hellendoorn afval

### ISSUE THREAD

**Issue by rhannink** [frenck/python-twentemilieu#4]
Hello,

I live in de gemeente Hellendoorn and our afvalkalender uses exactly the same API calls, parameters and URLS's as Twentemillieu. Only the Company Code differs. For Hellendoorn it is:

`24434f5b-7244-412b-9306-3a2bd1e22bc1`

Test zipcode is 7441AA with housenummer 121.

Can you please add this to your code? I can also fork your repository and change it myself, but it would be nice if it was Integrated. And I then might also be Able to use it with Home Assistant. Maybe you have Some ideas to create a switch or parameter between the two of them.

The community of Hellendoorn has a population of about 35.000 people.

Gr. Remco

**Comment by rhannink** [comment]
I changed the file const.py and changed the Company code into the code for Gemeente Hellendoorn. I now can use my zipcode (and 35.000 other residents) with Home Assistant. Maybe you can add this as a configuratie item

**Comment by jk-5** [comment]
`adc418da-d19b-11e5-ab30-625662870761` is the uuid for 'Area reiniging' in a big part of Drenthe. Would be nice if that could be added too.

Maybe this library should be generic for wasteapi and let users provide the company code. We could make a registry of well-known company codes in here for ease of use. @frenck If you agree on this, i will make the necessary code changes to this module as a PR, so we can get it ready. I am using my own custom module now for homeassistant which i have been using for a few years already. The twentemilieu integration works way better with config flow integration, so i would be happy to help to make this generic

**Comment by jk-5** [comment]
I made #43 to make this module generic, so a generic wasteapi can be made in homeassistant

**Comment by frenck** [comment]
Feel free to build a new Python module and add it to Home Assistant.
I'm not planning on supporting a shitload of area's support, that might change any time.

(I know from a fact from a resource, some are changing).
