### ISSUE TITLE
TwenteMileue.unique_id not working with empty house_letter

### ISSUE THREAD

**Issue by dennisschroer** [frenck/python-twentemilieu#59]
Hey. The setup of my homeassistant integration of TwenteMilieu was broken, but I could not complete the flow. I got the error "Address not found in Twente Milieu service area.". Since it worked before, I started debugging.

I found out that  this snippet works (removed address from example, note the space in house_letter):

```python
from twentemilieu import TwenteMilieu
import asyncio

async def test():
    twentemilieu = TwenteMilieu(
        post_code="postcode",
        house_number="number",
        house_letter=" ",
    )

    unique_id = await twentemilieu.unique_id()

loop = asyncio.get_event_loop()
loop.run_until_complete(test())
```

But this doesn't:

```python
from twentemilieu import TwenteMilieu
import asyncio

async def test():
    twentemilieu = TwenteMilieu(
        post_code="postcode",
        house_number="number",
        house_letter="",
    )

    unique_id = await twentemilieu.unique_id()

loop = asyncio.get_event_loop()
loop.run_until_complete(test())
```

Provinding an empty string in the houseLetter field of the POST reqeust to `https://wasteapi.2go-mobile.com/api/FetchAdress` seems to work fine.

Luckily I got my integration working again by entering a space in the setup flow of homeassistant.

**Comment by pinquin87** [comment]
Noticed the same issue since the update to HA 107.

Thanks for the workaround!
